name: Scheduled GET Request

# Trigger the workflow every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  get_request:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request
        run: |
          curl -X GET http://80.108.95.253:47989/
