name: Scheduled GET Request

on:
  push:
  schedule:
    - cron: '* * * * *'  # Runs every 1 minute


jobs:
  get_request:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request
        run: |
          curl -X GET http://80.108.95.253:47989/
