name: Scheduled GET Request

on:
  schedule:
    - cron: '30 14 * * *'  

jobs:
  get_request:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request
        run: |
          curl -X GET http://80.108.95.253:47989/
