name: Scheduled GET Request

on:
  schedule:
    - cron: '40 12 * * *'  # Runs every day at 12:40 UTC, equivalent to 14:40 CEST

jobs:
  get_request:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request
        run: |
          curl -X GET http://80.108.95.253:47989/
